/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Transaction {
  id: string; // Internal unique ID (can be autogenerated or use indices)
  pastedIndex: number; // The number at the beginning of the row e.g., 7, 8, etc.
  username: string; // e.g. semogahoki1221
  fullName: string; // e.g. ifnu juliawan
  accountNumber: string; // e.g. 081264183559
  paymentMethod: string; // e.g. DANA, BRI, BCA, etc.
  trxCode: string; // e.g. LGBDT-MW727604
  uuid1: string; // e.g. 019eea3f-1a8c-72c6-9ecc-80501474a2a5
  dateTime: string; // e.g. 2026-06-21 19:54:25
  amount: number; // e.g. 200000.0
  status: string; // e.g. wait for payment, success, failed
  uuid2: string; // e.g. fa660f3a-c4e0-4e91-9b0b-e8990d1e6379
  rawLine?: string; // The original pasted line text
}

export interface ImportSession {
  id: string;
  name: string;
  createdAt: string;
  transactions: Transaction[];
}

export type SortField = 'pastedIndex' | 'username' | 'fullName' | 'paymentMethod' | 'dateTime' | 'amount' | 'status';
export type SortOrder = 'asc' | 'desc';

export interface FilterOptions {
  searchQuery: string;
  paymentMethod: string;
  status: string;
  minAmount: string;
  maxAmount: string;
  startDate: string;
  endDate: string;
}

export interface ColumnMapping {
  pastedIndex: number;
  username: number;
  fullName: number;
  accountNumber: number;
  paymentMethod: number;
  trxCode: number;
  uuid1: number;
  dateTime: number;
  amount: number;
  status: number;
  uuid2: number;
}
